### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by jcuenod** [gavindinubilo/jam-api#24]
It looks dead...

**Comment by dinubs** [comment]
No, I've since made a successor to this project. I suggest everyone that wants something similar to use https://github.com/dinubs/coolqlcool

My reasoning for swapping is that this project was difficult to maintain and add new features to, whereas Cool QL Cool everything is much better organized.

It has quite a bit more features and is easier to maintain and deploy on your own (I highly suggest).

**Features**

* Nested selectors
* Query multiple sites at once
* Support for browser rendered websites (e.g. single page applications)
* Easily deployed on zeit.co

**Comment by jcuenod** [comment]
Could you add a comment in the readme on this project directing people to `coolqlcool`?

**Comment by dinubs** [comment]
@jcuenod Added to the readme.
